
-- CONSTRAINT.
-- DEFAULT VALUES


DROP TABLE IF EXISTS student;

CREATE TABLE student(
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(50) NOT NULL CHECK(LENGTH(name)>4),
    email VARCHAR(50) NOT NULL UNIQUE CHECK(LENGTH(name)>4),
    mark INTEGER NOT NULL DEFAULT 0,
    is_married BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT mark_is_valid CHECK (mark> -1 AND mark<101)
)
