CREATE TABLE parent(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE
);

CREATE TABLE student(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    parent_id INTEGER NOT NULL UNIQUE,
    FOREIGN KEY (parent_id) REFERENCES parent(id) ON DELETE CASCADE
);